services:
  chat-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: chat-server
    restart: always
    ports:
      - "8081:8081"
    networks:
      - chat_network

volumes:
  data:

networks:
  chat_network:
    driver: bridge