services:
  redis:
    image: redis:latest
    container_name: local_redis
    restart: always
    ports:
      - '${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
