version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
    container_name: member-email-server

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: member-redis
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379