services:
  postgres:
    image: postgres:latest
    container_name: space_db_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  space-server:
    build:
      context: ../backend/space-server
    container_name: space_server
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@space_db_postgres:5432/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: ["npm", "run", "start:dev"]

volumes:
  postgres_data:
