networks:
  space_network:
services:
  space-postgres:
    image: postgres:latest
    container_name: space_db_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - space_postgres_data:/var/lib/postgresql/data
    networks:
      - space_network

  space-redis:
    image: redis:latest
    container_name: space_db_redis
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - space_redis_data:/data
    networks:
      - space_network

  space-server:
    build:
      context: ../backend/space-server
    container_name: space_server
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@space_db_postgres:5432/mydatabase
      REDIS_HOST: space_db_redis
      REDIS_PORT: 6379
    ports:
      - "8090:8090"
    depends_on:
      - space-postgres
      - space-redis
    command: >
      sh -c "npx prisma migrate deploy && npx prisma generate && pnpm run start:dev"
    networks:
      - space_network

volumes:
  space_postgres_data:
  space_redis_data:
