services:
  redis:
    image: redis:latest
    container_name: auth_db_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
  auth-server:
    build:
      context: ../backend/auth-server
    container_name: auth-server
    restart: always
    environment:
      REDIS_HOST: auth_db_redis
      REDIS_PORT: 6379
    ports:
      - "8091:8091"
    depends_on:
      - redis
    command: pnpm run start:dev

volumes:
  redis_data:
