services:
  member-server:
    image: imjanghyeok/smiletogether-member-server:latest
    container_name: member-member-server
    restart: always
    ports:
      - 8080:8080
    networks:
      - smiletogether-network

networks:
  smiletogether-network:
    name: smiletogether-network
    driver: bridge