version: '3.8'

services:
  history-server:
    image: imjanghyeok/smiletogether-history-server:latest
    container_name: history-server
    restart: always
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://histuser:histpass@mongodb-history:27017/history-db?authSource=admin
    depends_on:
      - mongodb-history
    networks:
      - smiletogether-network

networks:
  smiletogether-network:
    name: smiletogether-network
    driver: bridge
