version: '3.8'

services:
  chat-server:
    image: imjanghyeok/smiletogether-chat-server:latest
    container_name: chat-server
    restart: always
    ports:
      - "8081:8081"
    networks:
      - smiletogether-network

networks:
  smiletogether-network:
    name: smiletogether-network
    driver: bridge
